# Generated by Django 3.2.7 on 2021-10-10 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(choices=[('None', 'None'), ('Management', 'Management'), ('Applied Science', 'Applied Scinece'), ('Engineering', 'Engineering'), ('Humanities', 'Humanities')], default='None', max_length=200)),
                ('level', models.CharField(choices=[('None', 'None'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('+2', '+2'), ('Diploma', 'Diploma')], default='None', max_length=200)),
                ('program', models.CharField(choices=[('Comuter Engineering', 'Computer Engineering'), ('MBS', 'MBS'), ('BBA', 'BBA'), ('MBBS', 'MBBS')], max_length=200)),
                ('sem', models.CharField(choices=[('first Year', 'first Year'), ('Second Year', 'Second Year'), ('First Sem', 'First Sem'), ('Third Sem', 'Third Sem'), ('10', '10')], max_length=200)),
                ('book_name', models.CharField(max_length=255)),
                ('edition', models.CharField(blank=True, max_length=25, null=True)),
                ('author', models.CharField(max_length=100)),
                ('published_By', models.CharField(blank=True, max_length=100)),
                ('cover_pic', models.ImageField(default='image/pdf.png', upload_to='image/')),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pic', models.ImageField(default='image/pdf.png', upload_to='image/')),
                ('text', models.TextField()),
            ],
        ),
    ]
