# Generated by Django 3.2.7 on 2021-09-12 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='sem',
            new_name='program',
        ),
    ]
