# Generated by Django 3.2.7 on 2021-10-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='program',
            field=models.CharField(choices=[('None', 'None'), ('Comuter Engineering', 'Computer Engineering'), ('MBS', 'MBS'), ('BBA', 'BBA'), ('MBBS', 'MBBS')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='sem',
            field=models.CharField(choices=[('None', 'None'), ('first Year', 'first Year'), ('Second Year', 'Second Year'), ('First Sem', 'First Sem'), ('Third Sem', 'Third Sem'), ('10', '10')], default='None', max_length=200),
        ),
    ]
