# Generated by Django 3.2.7 on 2021-10-02 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(upload_to='static/books/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
