# Generated by Django 3.2.7 on 2021-09-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_sem_semester_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
