# Generated by Django 3.2.7 on 2021-10-18 04:24

import books.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20211011_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandsOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(choices=[('None', 'None'), ('Management', 'Management'), ('Applied Science', 'Applied Scinece'), ('Engineering', 'Engineering'), ('Humanities', 'Humanities')], max_length=200)),
                ('level', models.CharField(choices=[('None', 'None'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('+2', '+2'), ('Diploma', 'Diploma')], max_length=200)),
                ('program', models.CharField(choices=[('None', 'None'), ('Comuter Engineering', 'Computer Engineering'), ('MBS', 'MBS'), ('BBA', 'BBA'), ('MBBS', 'MBBS')], max_length=200)),
                ('sem', models.CharField(choices=[('None', 'None'), ('first Year', 'first Year'), ('Second Year', 'Second Year'), ('First Sem', 'First Sem'), ('Third Sem', 'Third Sem'), ('10', '10')], max_length=200)),
                ('subject', models.CharField(max_length=255)),
                ('chapter', models.CharField(max_length=255)),
                ('note_by', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/handsout/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
        migrations.CreateModel(
            name='OldQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(choices=[('None', 'None'), ('Management', 'Management'), ('Applied Science', 'Applied Scinece'), ('Engineering', 'Engineering'), ('Humanities', 'Humanities')], max_length=200)),
                ('level', models.CharField(choices=[('None', 'None'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('+2', '+2'), ('Diploma', 'Diploma')], max_length=200)),
                ('program', models.CharField(choices=[('None', 'None'), ('Comuter Engineering', 'Computer Engineering'), ('MBS', 'MBS'), ('BBA', 'BBA'), ('MBBS', 'MBBS')], max_length=200)),
                ('sem', models.CharField(choices=[('None', 'None'), ('first Year', 'first Year'), ('Second Year', 'Second Year'), ('First Sem', 'First Sem'), ('Third Sem', 'Third Sem'), ('10', '10')], max_length=200)),
                ('subject', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(2015), books.models.max_value_current_year])),
                ('file', models.FileField(upload_to='uploads/oldquestion/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
    ]
