# Generated by Django 3.2.7 on 2021-10-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='pic',
            field=models.ImageField(default='images/man.png', upload_to='team/'),
        ),
    ]
