# Generated by Django 3.2.7 on 2021-10-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_ourteam_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='pic',
            field=models.ImageField(default='team/man.png', upload_to='team/'),
        ),
    ]
